"use client"

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';




// export const metadata = {
//   title: "Diya Spices",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const queryClient =new QueryClient();

  return (
   

   
        <QueryClientProvider client={queryClient}>
        {children}
        </QueryClientProvider>


    
  );
}
