// import { NextURL } from "next/dist/server/web/next-url";
// import { useRouter } from "next/router";
import { Suspense } from "react";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import SearchContextProvider from "./context/SearchContextProvider";





export const metadata = {
  title: "Diya Spices",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  // const queryClient =new QueryClient();

  return (
   

    <html lang="en">
      

      <body  className="flex flex-col justify-between ">
        <SearchContextProvider>
        <Header/>
        {children}
        <Footer/>
        </SearchContextProvider>

      </body>
    
    </html>
    // </Usecontext>

    
  );
}
